-- Top 20 highest spending customers
SELECT *
FROM customer_record
ORDER BY Purchase_Amount DESC
LIMIT 20;

-- Average spending by age
SELECT Age,
       ROUND(AVG(Purchase_Amount),2) AS Average_Spending
FROM customer_record
GROUP BY Age
ORDER BY Age;

-- Most popular product categories
SELECT Category,
       COUNT(*) AS Total_Customers
FROM customer_record
GROUP BY Category
ORDER BY Total_Customers DESC;


-- Revenue generated by each category
SELECT Category,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_record
GROUP BY Category
ORDER BY Total_Revenue DESC;

-- Customers who received a discount and spent above the average purchase amount
SELECT customer_id, purchase_amount
FROM customer_record
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer_record
  );

-- Top 5 products with the highest average review rating
SELECT item_purchased,
       AVG(review_rating) AS "Average Product Rating"
FROM customer_record
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Average purchase amount by shipping type 'Express' or 'Standard'

SELECT Shipping_type,
       ROUND(AVG(purchase_amount::NUMERIC), 2) AS average_purchase_amount
FROM customer_record
WHERE Shipping_type IN ('Express', 'Standard')
GROUP BY Shipping_type;

-- Average purchase amount and total revenue by subscription status
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount::NUMERIC), 2) AS average_purchase_amount,
       ROUND(SUM(purchase_amount::NUMERIC), 2) AS total_revenue
FROM customer_record
GROUP BY subscription_status;

-- Top 5 items purchased with discounts and their percentage of total purchases
SELECT item_purchased,
		  COUNT(purchase_amount) AS total_purchase_amount,
       ROUND(
           COUNT(purchase_amount) * 100.0 / SUM(COUNT(purchase_amount)) OVER () ,
           2
       ) AS purchase_amount_percentage  
FROM customer_record
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY purchase_amount_percentage DESC
limit 5;

-- Top 5 items purchased with the highest discount rate
SELECT item_purchased,
       ROUND(
           SUM(CASE
                   WHEN discount_applied = 'Yes' THEN 1
                   ELSE 0
               END) * 100.0 / COUNT(*),
           2
       ) AS discount_rate -- example discouted = 3 out of 5 so discount_rate = 3 * 100 / 5 = 60%
FROM customer_record
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--classifying customers based on their previous purchases
WITH customer_type AS (
    SELECT Customer_ID,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_record
)

SELECT customer_segment,
       COUNT(*) AS "No of Customers"
FROM customer_type
GROUP BY customer_segment;

