-- Top 20 highest spending customers
SELECT *
FROM customer_record
ORDER BY Purchase_Amount DESC
LIMIT 20;

-- Average spending by age
SELECT Age,
       ROUND(AVG(Purchase_Amount),2) AS Average_Spending
FROM customer_record
GROUP BY Age
ORDER BY Age;

-- Most popular product categories
SELECT Category,
       COUNT(*) AS Total_Customers
FROM customer_record
GROUP BY Category
ORDER BY Total_Customers DESC;

-- Revenue generated by each category
SELECT Category,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer_record
GROUP BY Category
ORDER BY Total_Revenue DESC;